name: Provision with Terraform and Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'sample-azure-function-python-app'
  PYTHON_VERSION: '3.9'

jobs:
  provision:
    runs-on: ubuntu-latest
    name: 🏗️ Provision Infrastructure with Terraform
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init -input=false

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -input=false

  deploy:
    runs-on: ubuntu-latest
    name: 🚀 Deploy Function Code
    needs: provision
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Setup Python Environment'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install Dependencies and Package'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          zip -r deployment.zip .

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: 'deployment.zip'